### PR TITLE
i think this is better

### PR DESCRIPTION
**Pull request by TacoTheDank**
how about it?

### CODE REVIEW

**Comment by tube42** [comment]
I see four different types of changes here:

1. updates to android versions, tools and so on
2. updates to files created automatically by libgdx, gradle and so on
3. automatic reformatting to XML and java files, probably by your editor
4. some text changes, for example in README.rst

Could you give me a PR that contains only part 1?

**Comment by TacoTheDank** [comment]
The java file changes weren't formatting changes; I edited those myself. I only changed necessary parts of the java files (i.e. removing imports that weren't being used, optimizing code, etc) and tried to change as little as possible. Also, I work in Android Studio and Notepad++ (which doesn't automatically change anything).

**Comment by TacoTheDank** [comment]
Nevertheless, I'll revert formatting changes and only push changes that actually benefit the project.

**Comment by TacoTheDank** [comment]
(removed previous commits and made these off of those, much fewer changes)

**Comment by tube42** [comment]
Sorry mate, this fails to build on my machine.

Have you tested building this without Android Studio (using gradle) or even better on the f-droid virtual machine?

**Comment by TacoTheDank** [comment]
Oh I forgot about this, no I haven't tested it without Android Studio... I'll try some stuff

**Pull request closed without merging**
