### PR TITLE
Code cleanup and adaptive icon

### PR DESCRIPTION
**Pull request by TacoTheDank**
Hey, it's been a while.

### Commit 1
- Add .iml and .idea to .gitignore

### Commit 2
- Updated fonts from https://fonts.google.com/specimen/Roboto and https://fonts.google.com/specimen/Roboto+Condensed

### Commit 3
- Cleaned up tons of unused imports
- (I did not authorize the IDE to do [this](https://github.com/tube42/drumon/pull/26/commits/942bdb6a9a39a2ddb0b6d157e270a9ef523ef2b2#diff-10c3867e91156b02740e6f09d955ea3aL30), I don't know why it went and did that anyway)

### Commits 4-11
- Miscellaneous lints were fixed

### Commit 12
- Created a rudimentary adaptive icon from the icon.svg in extras. The app icon will now look much nicer on Android devices.

### CODE REVIEW

**Review by tube42 — COMMENTED** [review]
Hi Taco, thanks for the pull request!

I assume these were mostly generated by an IDE or some refactoring tool? There are some good stuff in there, but some stuff I don't want to change for various reasons.


Commit 2 & 3:
I can't accept tool changes because they almost always break things on someones computer. Usually its on the build servers.


Commit 4
These fonts are used for creating bitmap fonts in libgdx. It happens in code so Android Studio cannot see where they are used.

Without them the app will crash.


Commit 5
I know it looks wrong, but the old code does exactly what I want it to do. I don't remember the exact reason this was added but it was needed to compile a specific version of the app for testing.


bitwise operations: 
Not 100% sure these are identical, have to check.


adaptive icons:
How will this work on older androids?

misc:
If you look at "Clean up declaration redundancies" and similar commits often fix two different issue. In this case, one is okay, but I don't like the other change.


I will try to merge a subset of your changes.

**Comment by TacoTheDank** [comment]
@tube42 Sounds good to me! I'll make some changes. I hope it improves it.

The adaptive icons will only work for Oreo and above, which is okay because regular icons were also made for versions below Oreo (the pngs).

**Comment by tube42** [comment]
I did a manual merge with some of the commits. 

The round and adaptive icons doesn't work with the way art files are processed here, I need to look into that first.

**Comment by TacoTheDank** [comment]
@tube42 Alright, thanks.

**Pull request closed without merging**
