### PR TITLE
bump android studio and dependencies, compile with java 1.8

### PR DESCRIPTION
**Pull request by TacoTheDank**
I did this through a text editor; no Android Studio.
- Android Studio 1.5.0 -> 3.2.1
- gdx 1.9.7 -> 1.9.9
- roboVM 2.3.1 -> 2.3.5
- ashley 1.7.0 -> 1.7.3
- ai 1.8.0 -> 1.8.1
- Gradle 2.10 -> 4.10.3
- make everything compile with java 1.8
- change android plugin from android to com.android.application
- buildToolsVersion 28.0.2 -> 28.0.3 in android/build.gradle
- remove redundant semicolons in android/build.gradle

### CODE REVIEW

**Comment by tube42** [comment]
Thanks, this looks so much better!

I cannot max all versions to latest the way you do since there are some incompatibilities across build environments (f-droid vs travis vs my computer) and tool combinations (e.g. gradle vs Android SDK) that make this fail. 

So I will probably need to pull this manually.

**Comment by tube42** [comment]
added this PR manually, see commit 035ebce092770efe5dc66efd910e8e39bc13be31

**Comment by TacoTheDank** [comment]
Yeah, thank you. I figured I would do it this way to minimize incompatibilities, so that if anything didn't build, it would probably be something you would need to change on your end.

**Comment by TacoTheDank** [comment]
Curious, what computer setup do you use that somehow causes all these incompatibilities?

Also why did you rename the applicationId? That would mean F-Droid needs to build yet another app. https://github.com/tube42/drumon/commit/5a21ef6b1807c2bc0b94ca33771cc19bfeaf86dc#diff-7ae5a9093507568eabbf35c3b0665732R21

**Comment by tube42** [comment]
Hmm, the ID change was not intentional.

Different machines have different combinations of the SDK and built tools. They are pretty large so not all of them can be installed on a small build server.

**Pull request closed without merging**
